version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
        environment:
          DEPLOY_HOST: 139.162.179.147
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          command: npm install
          name: Installing Dependencies

      - save_cache:
          paths:
            - node_modules
            - i-love-hue-2-client/node_modules
            - i-love-hue-2-server/node_modules
            - i-love-hue-2-client/src/assets/sound-tracks
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Running build script for master branch
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]
            then
              chmod u+x ./deployments/build_prod.sh
              npm run build_prod
              sudo apt install rsync
              ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/known_hosts
            fi

      #- add_ssh_keys:
      #      fingerprints:
      #        - 0f:aa:30:da:01:a2:de:9d:1e:5c:96:19:b5:a9:5f:c9


      - deploy:
          name: Deploy master branch
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]
            then
              chmod u+x ./deployments/deploy_prod.sh
              ./deployments/deploy_prod.sh
            fi
